(function() {var implementors = {};
implementors["futures"] = [];
implementors["futures_cpupool"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static, E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_cpupool/struct.CpuFuture.html\" title=\"struct futures_cpupool::CpuFuture\">CpuFuture</a>&lt;T, E&gt;",synthetic:false,types:["futures_cpupool::CpuFuture"]},];
implementors["ocl"] = [{text:"impl <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/struct.Event.html\" title=\"struct ocl::Event\">Event</a>",synthetic:false,types:["ocl::standard::event::Event"]},{text:"impl <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/struct.EventArray.html\" title=\"struct ocl::EventArray\">EventArray</a>",synthetic:false,types:["ocl::standard::event::EventArray"]},{text:"impl <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/struct.EventList.html\" title=\"struct ocl::EventList\">EventList</a>",synthetic:false,types:["ocl::standard::event::EventList"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/struct.FutureMemMap.html\" title=\"struct ocl::FutureMemMap\">FutureMemMap</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"ocl/traits/trait.OclPrm.html\" title=\"trait ocl::traits::OclPrm\">OclPrm</a> + 'static,&nbsp;</span>",synthetic:false,types:["ocl::async::future_mem_map::FutureMemMap"]},{text:"impl&lt;V, G&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/async/struct.FutureGuard.html\" title=\"struct ocl::async::FutureGuard\">FutureGuard</a>&lt;V, G&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;G: <a class=\"trait\" href=\"ocl/async/trait.OrderGuard.html\" title=\"trait ocl::async::OrderGuard\">OrderGuard</a>&lt;V&gt;,&nbsp;</span>",synthetic:false,types:["ocl::async::order_lock::FutureGuard"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"ocl/traits/trait.OclPrm.html\" title=\"trait ocl::traits::OclPrm\">OclPrm</a>&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/async/struct.FutureFlush.html\" title=\"struct ocl::async::FutureFlush\">FutureFlush</a>&lt;T&gt;",synthetic:false,types:["ocl::async::buffer_sink::FutureFlush"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"ocl/traits/trait.OclPrm.html\" title=\"trait ocl::traits::OclPrm\">OclPrm</a>&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"ocl/async/struct.FutureFlood.html\" title=\"struct ocl::async::FutureFlood\">FutureFlood</a>&lt;T&gt;",synthetic:false,types:["ocl::async::buffer_stream::FutureFlood"]},];
implementors["qutex"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"qutex/struct.FutureGuard.html\" title=\"struct qutex::FutureGuard\">FutureGuard</a>&lt;T&gt;",synthetic:false,types:["qutex::qutex::FutureGuard"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"qutex/struct.FutureReadGuard.html\" title=\"struct qutex::FutureReadGuard\">FutureReadGuard</a>&lt;T&gt;",synthetic:false,types:["qutex::qrw_lock::FutureReadGuard"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"qutex/struct.FutureWriteGuard.html\" title=\"struct qutex::FutureWriteGuard\">FutureWriteGuard</a>&lt;T&gt;",synthetic:false,types:["qutex::qrw_lock::FutureWriteGuard"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
